### ISSUE TITLE
Cannot read property 'mapBy' of undefined

### ISSUE THREAD

**Issue by chrismllr** [green-arrow/ember-cli-c3#3]
Line 68 of c3-chart.js

'data.columns' is undefined when there is no data, refreshing the graph throws this error...

`Uncaught TypeError: Cannot read property 'mapBy' of undefined`

**\* After digging a little deeper, the "data" object I feed to c3-chart seems to be expecting to have a "columns" key, but I am using the "JSON Data" type, which doesn't have that columns key

**Comment by chrismllr** [comment]
After digging a little deeper, the "data" object I feed to c3-chart seems to be expecting to have a "columns" key, but I am using the "JSON Data" type, which doesn't have that columns key

**Comment by robguilfoyle** [comment]
@green-arrow: Is there any plans to continue this work?

**Comment by green-arrow** [comment]
@robguilfoyle: Unfortunately I don't have a whole lot of time on my hands right now to maintain this. I created it for use at a previous employer, and ended up moving on to a different job where I'm not using it quite as extensively at the moment.

If you know of anyone that has time and would be interested in maintaining, please let me know.

@chrismllr: You're exactly right. Currently, there is really only support for the `row` and `column` types, not the `JSON` data type
